# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dffa7d465cdd5a75bd5f1d8884bfed1232fb89bac8a62e6a128004cb33ec71f83ef16cd8d10f63a5b2f70ba937ec8b50766b6601fb0cb865e51c15238fb48850

test:
  secret_key_base: baa1dd44b427bf8c6436a1be9a11da96c3e1c5d232713a139c556fb53a2685f5bc922c0f10b9da7fe2ae0583ec86fe7f8e31d78d7f6e8355adcb23787ae77c5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
